#!/usr/bin/env bash

# script that transfers a file from our client to a server.

if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi 
username="$3"
path_file="$1"
ip="$2"
path_ssh="$4"

scp -i "$path_ssh" "$path_file" "$username@$ip:~/"    
