#!/usr/bin/env bash
# script that installs and configures Nginx on the server

sudo apt-get update
sudo apt-get install -y nginx
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
